config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  dragonfly_accessor :photo

  def avatar_url(width = nil, height = nil)
    generate_avatar
    
    # @ToDo the host should be added only for mail,s investigate more about dragonfly configuration
    if ( width && height ) 
      photo.thumb("#{width}x#{height}").url host: Rails.application.config.action_mailer.asset_host
    else
      photo.url host: Rails.application.config.action_mailer.asset_host
    end
  rescue => e
    logger.error " ==== ERROR GENERATING IMAGE, CHECK user#avatar_url"
    logger.error e.message
    ActionController::Base.helpers.asset_path 'default-user.jpg'
  end

  def generate_avatar(force = false)
    if force || photo.nil?
      avatar = Dragonfly.app.generate(:initial_avatar, "#{first_name} #{last_name}", self.class::AVATAR_OPTIONS)
      update_attribute(:photo, avatar)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

   layout :layout


  def layout
    if devise_controller?
      'admin_login'
    else
      'admin'
    end
  end

  def home

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nickname, :photo, 
        :photo_uid, :email, :phone, :online, :password, :password_confirm)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def body_classes
    path = self.controller_path.split('/')
    namespace = path.second ? path.first : nil
    controller_name = params[:controller].gsub('/', '_')
    "#{namespace} controller_#{controller_name} action_#{params[:action]}"
  end
  
  def title(page_title)
    content_for(:title) { page_title }
  end
    
  def boolean_check(value)
    css_class = {
        NilClass => 'default',
      FalseClass => 'danger',
       TrueClass => 'success'
    }[value.class]

    icon = {
        NilClass => 'minus',
      FalseClass => 'ban',
       TrueClass => 'check'
    }[value.class]

    content_tag :span, class: "label label-#{css_class}" do
      content_tag :i, '', class: "fa fa-#{icon}"
    end
  end

  def badge(text = false, type: 'primary', &block)
    content_tag :span, class: "badge badge-#{type}" do
      block ? block.call : text
    end
  end

  def bs_label(text, type = 'primary', &block)
    content_tag :span, class: "label label-#{type}" do
      block ? block.call : text
    end
  end

  def progress_bar(percentage, type: nil)
    if type.nil?
      type = if percentage > 80 && percentage < 100
        'warning'
      elsif percentage >= 100
        'danger'
      else
        'info'
      end
  end
  
  # ToDO check what does this outside of a method... ?
  content_tag :div, class: 'progress' do
      tag :div, {
        class: "progress-bar progress-bar-#{type} animate-progress-bar",
        'data-percentage': "#{percentage}%"
      }

    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/home.html.haml
hola

app/views/elements/_error_details.haml
- if errors.any?
  #error_explanation
    %h2= _("%s prohibited this visit from being saved:") % pluralize(errors.count, "error")
    %ul
      - errors.full_messages.each do |msg|
        %li= msg

app/views/elements/_flash_session.haml
#flash_alerts.topspace_height
  - if notice
    .alert.alert-success
      %button.close{'data-dismiss' => 'alert'}
      %i.fa.fa-check
      = notice
  - if alert
    .alert.alert-warning
      %button.close{'data-dismiss' => 'alert'}
      %i.fa.fa-warning
      = alert
  - if flash[:error]
    .alert.alert-error
      %button.close{'data-dismiss' => 'alert'}
      %i.fa.fa-warning
      = flash[:error]


:javascript
  var flash_alerts = {
    notice: #{notice.to_json},
    alert:  #{alert.to_json},
    error: #{flash[:error].to_json},
  }
  

app/views/elements/_footer.haml
:javascript
  var loading_image = "#{asset_path 'default/loading2.gif'}"
  var minus_image = "#{asset_path 'icon/accodion_minus_icon.png'}"
  var plus_image = "#{asset_path 'icon/accodion_plus_icon.png'}"

/ START FOOTER
.container-fluid.container-fixed-lg.footer
  .copyright.sm-text-center
    %p.small.no-margin.pull-left.sm-pull-reset
      %span.hint-text ©
      %span.font-montserrat Prophio.com
      %span.sm-block
        |
        Need Support?
        %a.m-l-10{:href => "mailto:manolet@gmail.com"}
          escribe@prophio.com
    %p.small.no-margin.pull-right.sm-pull-reset
      %span.hint-text Created by
      %a{:href => "http://www.neyronbit.com"} NeyronBit 
      &
      %a{:href => "http://www.cognitus.com"} Cognitus
    .clearfix
/ END FOOTER

app/views/elements/_header.haml
/ START PAGE HEADER WRAPPER
/ START HEADER
.header
  / START MOBILE CONTROLS
  / LEFT SIDE
  .pull-left.full-height.visible-sm.visible-xs
    / START ACTION BAR
    .sm-action-bar
      %a.btn-link.toggle-sidebar{"data-toggle" => "sidebar", :href => "#"}
        %span.icon-set.menu-hambuger
    / END ACTION BAR
  / RIGHT SIDE
  .pull-right.full-height.visible-sm.visible-xs
    / START ACTION BAR
    .sm-action-bar
      %a.btn-link{"data-toggle" => "quickview", "data-toggle-element" => "#quickview", :href => "#"}
        %span.icon-set.menu-hambuger-plus
    / END ACTION BAR
  / END MOBILE CONTROLS
  .pull-left.sm-table
    .header-inner
      .brand.inline
        %img{:alt => "Prophio.com", "data-src" => image_path('logo.png'), "data-src-retina" => image_path('logo_white_2x.png'),:src => image_path('logo.png'), :height => "37"}/
      / BEGIN NOTIFICATION DROPDOWN
      %ul.notification-list.no-margin.hidden-sm.hidden-xs.b-grey.b-l.b-r.no-style.p-l-30.p-r-20
        %li.p-r-15.inline
          .dropdown
            /%a#notification-center.icon-set.globe-fill{"data-toggle" => "dropdown", :href => "javascript:;"}
            %a#notification-center{"data-toggle" => "dropdown", :href => "javascript:;"}
              %i.fa.fa-bell
              %span.bubble
            .dropdown-menu.notification-toggle{"aria-labelledby" => "notification-center", :role => "menu"}
              .notification-panel
                / START Notification Body
                .notification-body.scrollable
                  / START Notification Item
                  .notification-item.clearfix
                    .heading
                      %a.text-danger{:href => "#"}
                        %i.fa.fa-exclamation-triangle.m-r-10
                        %span.bold 98 Server Load
                        %span.fs-12.m-l-10 Take Action
                      %span.pull-right.time
                        2 mins ago
                    .option
                      %a.mark{:href => "#"}
                  / END Notification Item
                / END Notification Body
                / START Notification Footer
                .notification-footer.text-center
                  %a{:href => "#"} Read all notifications
                  %a.portlet-refresh.text-black.pull-right{"data-toggle" => "refresh", :href => "#"}
                    %i.pg-refresh_new
                / END Notification Footer
        / %li.p-r-15.inline
        /   %a.icon-set.globe-fill{:href => "#"}
        /   %b.big All Territories
      / END NOTIFICATION DROPDOWN
      %a.search-link{"data-toggle" => "search", :href => "#"}
        %i.pg-search>
        Type anywhere to
        %span.bold search

  .pull-right
    / START User Info
    .visible-lg.visible-md.m-t-10
      .pull-left.p-r-10.p-t-10.fs-16.font-heading
        %span.semi-bold= current_user.nickname
        %span.text-master
      .dropdown.pull-right
        %button.profile-dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
          %span.thumbnail-wrapper.d32.circular.inline.m-t-5
            %img#avatar{:alt => "", :height => "32", :src => current_user.avatar_url, :width => "32"}/
        %ul.dropdown-menu.profile-dropdown{:role => "menu"}
          %li
            = link_to edit_user_path(current_user) do
              %i.glyphicon.glyphicon-user
              %span.pull-right My Profile
          %li
            %a{:href => "#"}
              %i.pg-settings_small
              Settings
          %li
            %a{:href => "#"}
              %i.pg-outdent
              Feedback
          %li
            %a{:href => "#"}
              %i.pg-signals
              Help
          %li.bg-master-lighter
            = link_to(destroy_user_session_path, :method => :delete, class: 'clearfix') do
              %span.pull-left Logout
              %span.pull-right
                %i.pg-power

    / END User Info
/ END HEADER
/ END PAGE HEADER WRAPPER

app/views/elements/_overlay_search.haml
/ START OVERLAY
.overlay{"data-pages" => "search", :style => "display: none"}
  / BEGIN Overlay Content !
  .overlay-content.has-results.m-t-20
    / BEGIN Overlay Header !
    .container-fluid
      / BEGIN Overlay Logo !
      %img.overlay-brand{:alt => "logo", "data-src" => image_path('logo.png'), "data-src-retina" => image_path('logo_2x.png'), :height => "22", :src => image_path('logo.png'), :width => "78"}/
      / END Overlay Logo !
      / BEGIN Overlay Close !
      %a.close-icon-light.overlay-close.text-black.fs-16{:href => "#"}
        %i.pg-close
      / END Overlay Close !
    / END Overlay Header !
    .container-fluid
      / BEGIN Overlay Controls !
      %input#overlay-search.no-border.overlay-search.bg-transparent{:autocomplete => "off", :placeholder => "Search...", :spellcheck => "false"}/
      %br/
      .inline-block
        .checkbox.right
          %input#checkboxn{:checked => "checked", :type => "checkbox", :value => "1"}/
          %label{:for => "checkboxn"}
            %i.fa.fa-search
            Search within page
      .inline-block.m-l-10
        %p.fs-13 Press enter to search
      / END Overlay Controls !
    / BEGIN Overlay Search Results, This part is for demo purpose, you can add anything you like !
    .container-fluid
      %span
        %strong suggestions :
      %span#overlay-suggestions
      %br/
      .search-results.m-t-40
        %p.bold Pages Search Results
        .row
          .col-md-6
            / BEGIN Search Result Item !
            %div
              / BEGIN Search Result Item Thumbnail !
              .thumbnail-wrapper.d48.circular.bg-success.text-white.inline.m-t-10
                %div
                  %img{:alt => "", "data-src" => image_path('profiles/avatar.jpg'), "data-src-retina" => image_path('profiles/avatar2x.jpg'), :height => "50", :src => image_path('profiles/avatar.jpg'), :width => "50"}/
              / END Search Result Item Thumbnail !
              .p-l-10.inline.p-t-5
                %h5.m-b-5
                  %span.semi-bold.result-name ice cream
                  on pages
                %p.hint-text via john smith
            / END Search Result Item !
            / BEGIN Search Result Item !
            %div
              / BEGIN Search Result Item Thumbnail !
              .thumbnail-wrapper.d48.circular.bg-success.text-white.inline.m-t-10
                %div T
              / END Search Result Item Thumbnail !
              .p-l-10.inline.p-t-5
                %h5.m-b-5
                  %span.semi-bold.result-name ice cream
                  related topics
                %p.hint-text via pages
            / END Search Result Item !
            / BEGIN Search Result Item !
            %div
              / BEGIN Search Result Item Thumbnail !
              .thumbnail-wrapper.d48.circular.bg-success.text-white.inline.m-t-10
                %div
                  %i.fa.fa-headphones.large-text
              / END Search Result Item Thumbnail !
              .p-l-10.inline.p-t-5
                %h5.m-b-5
                  %span.semi-bold.result-name ice cream
                  music
                %p.hint-text via pagesmix
            / END Search Result Item !
          .col-md-6
            / BEGIN Search Result Item !
            %div
              / BEGIN Search Result Item Thumbnail !
              .thumbnail-wrapper.d48.circular.bg-info.text-white.inline.m-t-10
                %div
                  %i.fa.fa-facebook.large-text
              / END Search Result Item Thumbnail !
              .p-l-10.inline.p-t-5
                %h5.m-b-5
                  %span.semi-bold.result-name ice cream
                  on facebook
                %p.hint-text via facebook
            / END Search Result Item !
            / BEGIN Search Result Item !
            %div
              / BEGIN Search Result Item Thumbnail !
              .thumbnail-wrapper.d48.circular.bg-complete.text-white.inline.m-t-10
                %div
                  %i.fa.fa-twitter.large-text
              / END Search Result Item Thumbnail !
              .p-l-10.inline.p-t-5
                %h5.m-b-5
                  Tweats on
                  %span.semi-bold.result-name ice cream
                %p.hint-text via twitter
            / END Search Result Item !
            / BEGIN Search Result Item !
            %div
              / BEGIN Search Result Item Thumbnail !
              .thumbnail-wrapper.d48.circular.text-white.bg-danger.inline.m-t-10
                %div
                  %i.fa.fa-google-plus.large-text
              / END Search Result Item Thumbnail !
              .p-l-10.inline.p-t-5
                %h5.m-b-5
                  Circles on
                  %span.semi-bold.result-name ice cream
                %p.hint-text via google plus
            / END Search Result Item !
    / END Overlay Search Results !
  / END Overlay Content !
/ END OVERLAY

app/views/elements/_quickview.haml
/ START QUICKVIEW
#quickview.quickview-wrapper{"data-pages" => "quickview"}
  / Nav tabs
  %ul.nav.nav-tabs
    %li
      %a{"data-toggle" => "tab", :href => "#quickview-notes"} Notes
    %li
      %a{"data-toggle" => "tab", :href => "#quickview-alerts"} Alerts
    %li.active
      %a{"data-toggle" => "tab", :href => "#quickview-chat"} Techs
  %a.btn-link.quickview-toggle{"data-toggle" => "quickview", "data-toggle-element" => "#quickview"}
    %i.pg-close
  / Tab panes
  .tab-content
    / BEGIN Notes !
    #quickview-notes.tab-pane.fade.in.no-padding
      #note-views.view-port.clearfix.quickview-notes
        / BEGIN Note List !
        #quick-note-list.view.list
          .toolbar.clearfix
            %ul.pull-right
              %li
                %a.delete-note-link{:href => "#"}
                  %i.fa.fa-trash-o
              %li
                %a.new-note-link{"data-navigate" => "view", "data-view-animation" => "push", "data-view-port" => "#note-views", :href => "#"}
                  %i.fa.fa-plus
            %button.btn-remove-notes.btn.btn-xs.btn-block{:style => "display:none"}
              %i.fa.fa-times
              Delete
          %ul
            / BEGIN Note Item !
            %li{"data-navigate" => "view", "data-noteid" => "1", "data-view-animation" => "push", "data-view-port" => "#note-views"}
              .left
                / BEGIN Note Action !
                .checkbox.check-warning.no-margin
                  %input#qncheckbox1{:type => "checkbox", :value => "1"}/
                  %label{:for => "qncheckbox1"}
                / END Note Action !
                / BEGIN Note Preview Text !
                %p.note-preview Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam
                / BEGIN Note Preview Text !
              / BEGIN Note Details !
              .right.pull-right
                / BEGIN Note Date !
                %span.date 12/12/14
                %a{:href => "#"}
                  %i.fa.fa-chevron-right
                / END Note Date !
              / END Note Details !
            / END Note List !
        / END Note List !
        #quick-note.view.note
          %div
            %ul.toolbar
              %li
                %a.close-note-link{"data-navigate" => "view", "data-view-animation" => "push", "data-view-port" => "#note-views", :href => "#"}
                  %i.pg-arrow_left
              %li
                %a.Bold{:href => "#"}
                  %i.fa.fa-bold
              %li
                %a.Italic{:href => "#"}
                  %i.fa.fa-italic
              %li
                %a{:href => "#"}
                  %i.fa.fa-link
            .body
              %div
                .top
                  %span 21st april 2014 2:13am
                .content
                  .quick-note-editor.full-width.full-height.js-input{:contenteditable => "true"}
    / END Notes !
    / BEGIN Alerts !
    #quickview-alerts.tab-pane.fade.no-padding
      #alerts.view-port.clearfix
        / BEGIN Alerts View !
        .view.bg-white
          / BEGIN View Header !
          .navbar.navbar-default.navbar-sm
            .navbar-inner
              / BEGIN Header Controler !
              %a.inline.action.p-l-10.link.text-master{"data-navigate" => "view", "data-view-animation" => "push-parrallax", "data-view-port" => "#chat", :href => "javascript:;"}
                %i.pg-more
              / END Header Controler !
              .view-heading
                Notications
              / BEGIN Header Controler !
              %a.inline.action.p-r-10.pull-right.link.text-master{:href => "#"}
                %i.pg-search
              / END Header Controler !
          / END View Header !
          / BEGIN Alert List !
          .list-view.boreded.no-top-border{"data-init-list-view" => "ioslist"}
            / BEGIN List Group !
            .list-view-group-container
              / BEGIN List Group Header!
              .list-view-group-header.text-uppercase
                Technicians
              / END List Group Header!
              %ul
                / BEGIN List Group Item!
                %li.alert-list
                  / BEGIN Alert Item Set Animation using data-view-animation !
                  %a{"data-navigate" => "view", "data-view-animation" => "push-parrallax", "data-view-port" => "#chat", :href => "javascript:;"}
                    %p.col-xs-height.col-middle
                      %span.text-warning.fs-10
                        %i.fa.fa-circle
                    %p.p-l-10.col-xs-height.col-middle.col-xs-9.overflow-ellipsis.fs-12
                      %span.text-master Uploaded Picture
                    %p.p-r-10.col-xs-height.col-middle.fs-12.text-right
                      %span.text-warning
                        Today
                        %br/
                      %span.text-master All Day
                  / END Alert Item!
                  / BEGIN List Group Item!
                / END List Group Item!
            / END List Group !
          / END Alert List !
        / EEND Alerts View !
    / END Alerts !
    #quickview-chat.tab-pane.fade.in.active.no-padding
      #chat.view-port.clearfix
        .view.bg-white
          / BEGIN View Header !
          .navbar.navbar-default
            .navbar-inner
              / BEGIN Header Controler !
              %a.inline.action.p-l-10.link.text-master{"data-navigate" => "view", "data-view-animation" => "push-parrallax", "data-view-port" => "#chat", :href => "javascript:;"}
                %i.pg-plus
              / END Header Controler !
              .view-heading
                Technician List
                .fs-11 Show All
              / BEGIN Header Controler !
              %a.inline.action.p-r-10.pull-right.link.text-master{:href => "#"}
                %i.pg-more
              / END Header Controler !
          / END View Header !
          .list-view.boreded.no-top-border{"data-init-list-view" => "ioslist"}
            .list-view-group-container
              .list-view-group-header.text-uppercase
                On site
              %ul
                / BEGIN Chat User List Item  !
                %li.chat-user-list.clearfix
                  %a{"data-navigate" => "view", "data-view-animation" => "push-parrallax", "data-view-port" => "#chat", :href => "#"}
                    %span.col-xs-height.col-middle
                      %span.thumbnail-wrapper.d32.circular.bg-success
                        / %img.col-top{:alt => "", :height => "34", :src => User.last.avatar_url, :width => "34"}/
                    %p.p-l-10.col-xs-height.col-middle.col-xs-12
                      %span.text-master Shane Merem
                      %span.block.text-master.hint-text.fs-12 Starbucks #1234 - Since 9:00 am
                / END Chat User List Item  !
            .list-view-group-container
              .list-view-group-header.text-uppercase Offline
              %ul
                / BEGIN Chat User List Item  !
                %li.chat-user-list.clearfix
                  %a{"data-navigate" => "view", "data-view-animation" => "push-parrallax", "data-view-port" => "#chat", :href => "#"}
                    %span.col-xs-height.col-middle
                      %span.thumbnail-wrapper.d32.circular.bg-success
                        / %img.col-top{:alt => "", :height => "34", :src => current_user.avatar_url, :width => "34"}/
                    %p.p-l-10.col-xs-height.col-middle.col-xs-12
                      %span.text-master Nehemiah
                      %span.block.text-master.hint-text.fs-12 --
                / END Chat User List Item  !
        / BEGIN Conversation View  !
        .view.chat-view.bg-white.clearfix
          / BEGIN Header  !
          .navbar.navbar-default
            .navbar-inner
              %a.link.text-master.inline.action.p-l-10{"data-navigate" => "view", "data-view-animation" => "push-parrallax", "data-view-port" => "#chat", :href => "javascript:;"}
                %i.pg-arrow_left
              .view-heading
                Shane Merem
                .fs-11.hint-text Online
              %a.link.text-master.inline.action.p-r-10.pull-right{:href => "#"}
                %i.pg-more
          / END Header  !
          / BEGIN Conversation  !
          #my-conversation.chat-inner
            / BEGIN From Me Message  !
            .message.clearfix
              .chat-bubble.from-me
                Hello there
            / END From Me Message  !
            / BEGIN From Them Message  !
            .message.clearfix
              .profile-img-wrapper.m-t-5.inline
                %img.col-top{:alt => "", "data-src" => current_user.avatar_url, "data-src-retina" => image_path('profiles/avatar_small2x.jpg'), :height => "30", :src => current_user.avatar_url, :width => "30"}/
              .chat-bubble.from-them
                Hey
            / END From Them Message  !
            / BEGIN From Me Message  !
            .message.clearfix
              .chat-bubble.from-me
                Did you check out Pages framework ?
            / END From Me Message  !
            / BEGIN From Me Message  !
            .message.clearfix
              .chat-bubble.from-me
                Its an awesome chat
            / END From Me Message  !
            / BEGIN From Them Message  !
            .message.clearfix
              .profile-img-wrapper.m-t-5.inline
                %img.col-top{:alt => "", "data-src" => current_user.avatar_url, "data-src-retina" => image_path('profiles/avatar_small2x.jpg'), :height => "30", :src => current_user.avatar_url, :width => "30"}/
              .chat-bubble.from-them
                Yea
            / END From Them Message  !
          / BEGIN Conversation  !
          / BEGIN Chat Input  !
          .b-t.b-grey.bg-white.clearfix.p-l-10.p-r-10
            .row
              .col-xs-1.p-t-15
                %a.link.text-master{:href => "#"}
                  %i.fa.fa-plus-circle
              .col-xs-8.no-padding
                %input.form-control.chat-input{"data-chat-conversation" => "#my-conversation", "data-chat-input" => "", :placeholder => "Say something", :type => "text"}/
              .col-xs-2.link.text-master.m-l-10.m-t-15.p-l-10.b-l.b-grey.col-top
                %a.link.text-master{:href => "#"}
                  %i.pg-camera
          / END Chat Input  !
        / END Conversation View  !
/ END QUICKVIEW

app/views/elements/_sidebar.haml
/ BEGIN SIDEBAR
#sidebar.page-sidebar{"data-pages" => "sidebar", 'data-turbolinks-permanent': ''}
  #appMenu.sidebar-overlay-slide.from-top

  / BEGIN SIDEBAR HEADER
  .sidebar-header
    %img.brand{:alt => "logo", "data-src" => image_path('logo_white.png'), "data-src-retina" => image_path('logo_white_2x.png'), :src => image_path('logo_white.png'), :width => "120", :height => "32 "}/
    .sidebar-header-controls.pull-rights
      %button.btn.btn-xs.sidebar-slide-toggle.btn-link{"data-pages-toggle" => "#appMenu", :type => "button"}
        %i.fa.fa-angle-down.fs-16
      %button.btn.btn-link.btn-toggle-layout.visible-md-inline.visible-lg-inline{'data-action' => "menuDefault",  type: "button", 'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'data-pin-label' => _('Pin navigation'), 'data-unpin-label' => _('Unpin navigation'), title: _('Toggle navigation',)}
        %i.fa.fa-thumb-tack
  / END SIDEBAR HEADER

  / BEGIN SIDEBAR MENU
  .sidebar-menu
    %ul.menu-items
      %li.m-t-30
        = link_to root_path, class: 'detailed' do
          %span.title Home
          %span.details 0 notifications
        %span.icon-thumbnail
          %i.pg-home
      %li
        = link_to users_path do
          Users
        %span.icon-thumbnail
          %i.fa.fa-university

        / %li
        /   = link_to properties_path do
        /     %span.title Properties
        /   %span.icon-thumbnail
        /     %i.fa.fa-home

        / %li
        /   = link_to residents_path do
        /     %span.title Residents
        /   %span.icon-thumbnail
        /     %i.fa.fa-user
    .clearfix
  / END SIDEBAR MENU
/ END SIDEBAR

app/views/users/index.html.haml
.row
  .col-md-12
    .grid.simple
      .grid-body.no-border
        %h1
          Users
        .panel-group
          .panel.panel-default
            .panel-body    
              %table.table.no-more-tables
                %thead
                  %tr
                    %th
                    %th Name
                    %th Email
                    %th Document
                    %th Phone
                    %th Online
                    %th Options
                %tbody
                  - @users.each do |user|
                    %tr
                      %td
                        %img.img-circle{src: user.avatar_url(42, 42)}
                      %td
                        = user.nickname
                        = user.email
                        = user.phone
                      %td
                        = user.email
                      %td
                        = link_to 'Edit', edit_user_path(user), class: 'btn btn-xs'

              
              = link_to "New User", new_user_path, class: 'btn btn-primary btn-cons'\
              = link_to _("Back"), root_path, class: 'btn btn-cons'

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path